import {
  faArrowLeft,
  faArrowRight,
  faArrowTrendDown,
  faArrowTrendUp,
  faBars,
  faBell as fasBell,
  faBolt,
  faCalendarDays,
  faCamera,
  faCheck,
  faCircleCheck,
  faChevronLeft,
  faChevronRight,
  faCity,
  faClockRotateLeft,
  faTriangleExclamation,
  faFilePen,
  faFire,
  faGlobe,
  faHardHat,
  faHeart,
  faLightbulb,
  faListCheck,
  faLocationCrosshairs,
  faLocationDot,
  faMagnifyingGlass,
  faMapLocationDot,
  faMapMarker,
  faQuoteLeft,
  faRightFromBracket,
  faRotateLeft,
  faRotateRight,
  faShieldHalved,
  faSun,
  faXmark,
  faUserPlus,
  faUsers,
  faUser,
  faChartBar,
  faRoute,
  faEye,
  faGears,
  faScrewdriverWrench,
  faLock,
  faKey,
  faEnvelope,
  faEyeSlash,
  faLandmark,
  faClipboardList,
  faSpinner
} from '@fortawesome/free-solid-svg-icons';

import {
  faCalendar as farCalendar,
  faClock as farClock,
  faImage as farImage,
  faMap as farMap,
  faBell as farBell
} from '@fortawesome/free-regular-svg-icons';

import {
  faFacebook,
  faLinkedin,
  faXTwitter
} from '@fortawesome/free-brands-svg-icons';

export const appIcons = [
  // Solid
  faArrowLeft,
  faArrowRight,
  faArrowTrendDown,
  faArrowTrendUp,
  faBars,
  fasBell,
  faBolt,
  faCalendarDays,
  faCamera,
  faCheck,
  faCircleCheck,
  faChevronLeft,
  faChevronRight,
  faCity,
  faClockRotateLeft,
  faTriangleExclamation,
  faFilePen,
  faFire,
  faGlobe,
  faHardHat,
  faHeart,
  faLightbulb,
  faListCheck,
  faLocationCrosshairs,
  faLocationDot,
  faMagnifyingGlass,
  faMapLocationDot,
  faMapMarker,
  faQuoteLeft,
  faRightFromBracket,
  faRotateLeft,
  faRotateRight,
  faShieldHalved,
  faSun,
  faXmark,
  faUserPlus,
  faUsers,
  faUser,
  faChartBar,
  faRoute,
  faEye,
  faGears,
  faScrewdriverWrench,
  faLock,
  faKey,
  faEnvelope,
  faEyeSlash,
  faLandmark,
  faClipboardList,
  faSpinner,
  // Regular
  farCalendar,
  farClock,
  farImage,
  farMap,
  farBell,
  // Brands
  faFacebook,
  faLinkedin,
  faXTwitter
];
